### ISSUE TITLE
Can't upload playlists that span multiple sectionIDs

### ISSUE THREAD

**Issue by mattspitz** [XDGFX/PPP#1]
I have two libraries, "Singles" and "Albums", and a playlist that spans both.

The script only specifies a single `sectionId` as a query parameter, and an upload appears to replace an existing playlist (vs. append), so it looks like I can do only one or the other.

I tried the following to pass two sectionIDs to the API to no avail:

- `sectionID=1&sectionID=2` (just takes the first one)
- `sectionID=1,2` (500)
- `sectionID[]=1&sectionID[]=2` (bad request)

Any ideas? Thanks for putting this together!

**Comment by XDGFX** [comment]
As you indicated, this is more of a problem with the API. Possibly you could create a new section which has all your music and use that one for playlists only? It would be kind of annoying having an extra section but you could at least hide it from your dashboard.

**Comment by mattspitz** [comment]
Yep, that's what I ended up doing as a workaround. And you're right, it's a
limitation of the API. I raised the issue on the Plex forums.

Thanks for following up!
