### ISSUE TITLE
Smart playlists

### ISSUE THREAD

**Issue by cswrd** [XDGFX/PPP#13]
I've managed to extract playlists from Plex 3.0.1. Support for smart playlists as 1-way sync / export would be nice.

Nevertheless there is a workaround to use PPP with smart playlists right now: clear the current playlist. Add the smart playlist to the current playlist so that only those songs are currently played. Save the current playlist to a regular playlist.

FYI: I'd use it to extract star rated songs as playlists and re-import them in WMP. WMP can batch rate songs from a playlist. Those song ratings are saved by WMP in the songs itself, improving backup safety of that information a lot. I spent a lot of time with rating my music actually.

**Comment by XDGFX** [comment]
I didn't bother with support for smart playlists because generally Plex and your local media player will have smart playlist capabilities, so it makes more sense to just make the smart playlist on both. That way they both automatically update regardless of PPP. 

I don't quite understand what you mean with regards to star rated songs?

**Comment by cswrd** [comment]
In simple scenarios different media players may share the exact same set of meta information and offer the same smart playlist capabilities. Song ratings are one example of a very proprietary meta information upon media players which won't be shared among them automatically. Plex stores them in its own database on a per user basis. Windows Media Player (WMP) can also embed them globally in each song file directly.

I use plex to rate songs. But those ratings are not available in Windows Media Player (WMP) automatically. So they have to be migrated to WMP somehow manually atm (automatically and on a regular basis would be better). Therefore, I create a smart plex playlist for each rating value and export them as indivdual m3u playlists with PPP. In WMP I can open e.g. the playlist "5 star rated songs", select all songs and rate them with 5 stars at once.

Doing so, I have the song ratings also available in WMP (saved globally in each file). I make a daily backup of my Plex server. However, the export of the ratings as playlists increases the backup quality of this handmade meta information further, because they are part of daily backups, too. I've already lost a bunch of my ratings in the past, I've spent hundreds of hours for.
