### ISSUE TITLE
automatically removes directories named 'tmp'

### ISSUE THREAD

**Issue by akhepcat** [XDGFX/PPP#2]
Instead of removing directories named 'tmp'  at the top of your script,  you should utilize the python method to security create a temporary directory ( https://docs.python.org/2/library/tempfile.html )  that way you're not impacting anything that might already exist.

isolation of temporary directories and files is always the more secure and safer option.

**Comment by XDGFX** [comment]
This is a great idea! I just updated to use tempfile.

**Comment by XDGFX** [comment]
Needed to revert to v2.0 as stuff was breaking; will re-implement this soon

**Comment by XDGFX** [comment]
So it looks like maybe this isn't so suitable in this case; PPP needs a directory accessible by both the machine running PPP (obviously), and a Plex machine. Assuming your Plex machine and PPP machine are different - playlists would need to be copied from the secure temp directory back into a shared or installation directory, which seems to defeat the purpose of using a secure temp directory in the first place.

Maybe in the future I can set it to use the temp directory properly, but for now I think it makes the most sense to use a tmp folder in the install directory.
