### ISSUE TITLE
Issues on First Launch

### ISSUE THREAD

**Issue by zer0wing42** [XDGFX/PPP#33]
Using Python 3.9 for Windows 10 (64-bit)
Using PPP.py v3.0.6

On first run, when I expect SETUP to run, launching PPP.py just crashes the Python window. Any suggestions? 
I can open the Python terminal window on its own just fine. Do I need to edit 'example-variables.json' before SETUP can run?

**Comment by Goldmaster** [comment]
Hi there, im having this issue. did you fix it?
