### ISSUE TITLE
"This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page."

### ISSUE THREAD

**Issue by leninsaccountant** [XDGFX/PPP#34]
Hello, 

I am trying to install PPP. I already have Python 3 installed, and I downloaded the PPP zip and extracted it with 7zip.

In the command window, I navigate to the extracted folder and try running: PPP.py -setup

I get the following error:

"This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page."

**Comment by XDGFX** [comment]
It sounds like you've just launched command prompt. Try the same but use the command `python3 PPP.py` or maybe `python PPP.py`

**Comment by XDGFX** [comment]
Closing as no reply from OP
