### ISSUE TITLE
Script runs fine with no errors, but no playlists are showing in plex

### ISSUE THREAD

**Issue by ArbiterGR** [XDGFX/PPP#7]
Hello, i've been trying to figure out why this doesn't work.

I'm running plex on a docker container and the script from a ubuntu VM. i make sure that the directories are visible from both plex container and the vm. i edited the variables and the script runs fine with no errors. But no playlists are being uploaded to the server.

What am i doing wrong?

**Comment by ArbiterGR** [comment]
I figured it out.

Line 229. You hard code the tmp/plex path assuming that this is a windows machine it's running on. i just had to convert \\\\tmp\\\\plex\\\\ to /tmp/plex/ to make it work. 

ps: Amazing script dude!

**Comment by Blackhawke** [comment]
> I figured it out.
> 
> Line 229. You hard code the tmp/plex path assuming that this is a windows machine it's running on. i just had to convert \\tmp\\plex\\ to /tmp/plex/ to make it work.
> 
> ps: Amazing script dude!

Yup! Just had the same problem on my linux box. Made that one little tweek and it worked like a charm. 

Amazing, script dude!

P.S. Might wanna check the OS and fix that some day.

**Comment by XDGFX** [comment]
Glad you worked it out! Closing the issue
