### ISSUE TITLE
doesnt seam to work in windows

### ISSUE THREAD

**Issue by Goldmaster** [XDGFX/PPP#9]
not sure if i have set this up or what but it doesn't seam to be working. I trying this out in windows 10. i have tried the line 229 fix but that doesn't work.

**Comment by samplethief** [comment]
Same for me.

**Comment by XDGFX** [comment]
Could you give some more info please? In what way is it not working?

**Comment by XDGFX** [comment]
Closed due to inactivity

**Comment by Goldmaster** [comment]
hi there it works sort off. i followed though with making the edits and seams to run ok. but when i go onto plex web, i see only 2 playlists out off the 7 i have and only 3 tracks and the loads of music i have in a playlist added.
